### ISSUE TITLE
Ein-/Aus-Schalter wäre nett

### ISSUE THREAD

**Issue by cboltz** [casartar/MacherDaachBadgeHardware#3]
Ausschalten ohne Ausbau der Batterie für 2-4 cent hört sich IMHO sinnvoll an ;-)

z. B. https://www.aliexpress.com/store/product/50Pcs-Mini-7-Pin-On-Off-1P2T-SPDT-MSK-12C02-SMD-Toggle-Slide-Switch-For-MP3/1766366_32856542440.html oder https://www.aliexpress.com/store/product/10pcs-Interruptor-On-off-Mini-Slide-Switch-SS12D00-SS12D00G3-3pin-1P2T-2-Position-High-Quality-Toggle/2336003_32860611275.html

oder gleich die Großpackung: https://www.aliexpress.com/store/product/200PCS-Vertical-Slide-Switch-High-Knob-3P-2-Position-1P2T-SPDT-0-5A-50V-DC-3mm/2260001_32813656155.html

(Suchbegriff: switch slide)

**Comment by casartar** [comment]
Es ist ja dann ein Jumper geworden.
